// <auto-generated />
namespace Kostagram_1._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IzmenaPoruka : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IzmenaPoruka));
        
        string IMigrationMetadata.Id
        {
            get { return "201609091305471_IzmenaPoruka"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
